---
- hosts: all

  vars:
    project_dir: "/home/ubuntu/tilemill/project"
    db:
      name: gis
      encoding: UTF-8

  tasks:

  - name: Create a database `{{ db.name }}`
    become: yes
    become_user: postgres
    postgresql_db:
      name: "{{ db.name }}"
      encoding: "{{ db.encoding }}"
      owner: ubuntu
      template: template0

  - name: Run SQL `CREATE EXTENSION IF NOT EXISTS hstore;`
    become: yes
    become_user: postgres
    shell: "psql -c \"CREATE EXTENSION IF NOT EXISTS hstore;\" -d {{ db.name }}"

  - name: Run SQL `CREATE EXTENSION IF NOT EXISTS postgis;`
    become: yes
    become_user: postgres
    shell: "psql -c \"CREATE EXTENSION IF NOT EXISTS postgis;\" -d {{ db.name }}"

  # OpenStreetMap Carto
  - name: Clone the openstreetmap-carto
    become: yes
    become_user: ubuntu
    git:
      repo: https://github.com/gravitystorm/openstreetmap-carto.git
      dest: "{{ project_dir }}/openstreetmap-carto"
      update: no

  - name: Import the default data
    become: yes
    become_user: ubuntu
    shell: "osm2pgsql --slim -d gis -C 3600 --cache 2048 --hstore -S {{ project_dir }}/openstreetmap-carto/openstreetmap-carto.style /opt/provision/default.osm"
    args:
      chdir: "{{ project_dir }}/openstreetmap-carto"

  - name: Run `./scripts/get-shapefiles.py`
    become: yes
    become_user: ubuntu
    shell: ./scripts/get-shapefiles.py
    args:
      chdir: "{{ project_dir }}/openstreetmap-carto"

  - name: Run `carto project.mml > style.xml`
    become: yes
    become_user: ubuntu
    shell: carto project.mml > style.xml
    args:
      chdir: "{{ project_dir }}/openstreetmap-carto"
